version: "3.8"
name: "mock-pipeline"
services:
  mongo-service:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - shared-data:/data/db

    networks:
    - mongo_net
  
  postgres-service:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydatabase"

    volumes:
      - shared-data:/var/lib/postgres/data
    
    networks:
    - mongo_net
  
  fastapi-service:
    build: 
      context: ./data_collector
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - 8000:8000
    depends_on:
      postgres-service:
        condition: service_started
      mongo-service:
        condition: service_started
    volumes:
      - shared-data:/fast_app_dir

    networks:
      - mongo_net

  scheduled_eljob_service:
    build:
      context: ./data_extractor_loader
      dockerfile: Dockerfile
    container_name: eljob
    depends_on:
      fastapi-service:
        condition: service_started
    networks:
      - mongo_net
  
  dashboard_marketing_service:
    build:
      context: ./marketing
      dockerfile: Dockerfile
    container_name: dashboard_marketing
    ports:
      - 8001:8000
    depends_on: 
      scheduled_eljob_service:
        condition: service_started
    networks:
      - mongo_net
    
      

networks:
  mongo_net:
    driver: bridge

volumes:
  shared-data:
    
    